// Draft-19 codec entry point

export const DRAFT_VERSION = 0xff000013n

export type { Draft19Codec } from './codec.js'
export {
  createDataStreamDecoder,
  createDraft19Codec,
  createFetchStreamDecoder,
  createStreamDecoder,
  createSubgroupStreamDecoder,
  decodeDatagram,
  decodeDataStream,
  decodeFetchStream,
  decodeMessage,
  decodeSubgroupStream,
  encodeDatagram,
  encodeFetchStream,
  encodeMessage,
  encodeSubgroupStream,
} from './codec.js'
export type {
  DataStreamResetCodeValue,
  PublishDoneCodeValue,
  RequestErrorCodeValue,
  SessionTerminationCodeValue,
} from './error-codes.js'
export {
  DataStreamResetCode,
  PublishDoneCode,
  RequestErrorCode,
  SessionTerminationCode,
} from './error-codes.js'

export {
  MESSAGE_ID_MAP,
  MESSAGE_TYPE_MAP,
  MSG_FETCH,
  MSG_FETCH_OK,
  MSG_GOAWAY,
  MSG_NAMESPACE,
  MSG_NAMESPACE_DONE,
  MSG_PUBLISH,
  MSG_PUBLISH_DONE,
  MSG_PUBLISH_NAMESPACE,
  MSG_PUBLISH_OK,
  MSG_PUBLISH_SKIPPED,
  MSG_REQUEST_ERROR,
  MSG_REQUEST_OK,
  MSG_REQUEST_UPDATE,
  MSG_SETUP,
  MSG_SUBSCRIBE,
  MSG_SUBSCRIBE_NAMESPACE,
  MSG_SUBSCRIBE_OK,
  MSG_SUBSCRIBE_TRACKS,
  MSG_TRACK_STATUS,
  SETUP_OPT_AUTHORITY,
  SETUP_OPT_AUTHORIZATION_TOKEN,
  SETUP_OPT_MAX_AUTH_TOKEN_CACHE_SIZE,
  SETUP_OPT_MAX_FILTER_RANGES,
  SETUP_OPT_MAX_REQUEST_UPDATES,
  SETUP_OPT_MOQT_IMPLEMENTATION,
  SETUP_OPT_PATH,
} from './messages.js'

export {
  BIDIRECTIONAL_MESSAGES,
  CLIENT_ONLY_MESSAGES,
  CONTROL_MESSAGES,
  getLegalIncoming,
  getLegalOutgoing,
  SERVER_ONLY_MESSAGES,
} from './rules.js'
export type {
  ProtocolViolation,
  SessionPhase,
  SideEffect,
  TransitionResult,
  ValidationResult,
} from './session.js'
export { createDraft19SessionState, Draft19SessionFSM } from './session.js'

export type {
  DatagramObject,
  DataStreamEvent,
  DataStreamHeader,
  Draft19BaseMessage,
  Draft19DataStream,
  Draft19Fetch,
  Draft19FetchOk,
  Draft19GoAway,
  Draft19Message,
  Draft19MessageType,
  Draft19Namespace,
  Draft19NamespaceDone,
  Draft19Params,
  Draft19Publish,
  Draft19PublishDone,
  Draft19PublishNamespace,
  Draft19PublishSkipped,
  Draft19RequestError,
  Draft19RequestOk,
  Draft19RequestUpdate,
  Draft19Setup,
  Draft19SetupOptions,
  Draft19Subscribe,
  Draft19SubscribeNamespace,
  Draft19SubscribeOk,
  Draft19SubscribeTracks,
  Draft19TrackProperties,
  Draft19TrackStatus,
  FetchObjectPayload,
  FetchStream,
  FetchStreamHeader,
  JoiningFetch,
  LargestObject,
  LocationFilter,
  ObjectPayload,
  RangeFilter,
  RangeFilterRange,
  Redirect,
  StandaloneFetch,
  SubgroupStream,
  SubgroupStreamHeader,
  UnknownParam,
} from './types.js'
