// Draft-17 codec entry point

export const DRAFT_VERSION = 0xff000011n

export type { Draft17Codec } from './codec.js'
export {
  createDataStreamDecoder,
  createDraft17Codec,
  createFetchStreamDecoder,
  createStreamDecoder,
  createSubgroupStreamDecoder,
  decodeDatagram,
  decodeDataStream,
  decodeFetchStream,
  decodeMessage,
  decodeSubgroupStream,
  encodeDatagram,
  encodeFetchStream,
  encodeMessage,
  encodeSubgroupStream,
} from './codec.js'

export {
  MESSAGE_ID_MAP,
  MESSAGE_TYPE_MAP,
  MSG_FETCH,
  MSG_FETCH_OK,
  MSG_GOAWAY,
  MSG_NAMESPACE,
  MSG_NAMESPACE_DONE,
  MSG_PUBLISH,
  MSG_PUBLISH_BLOCKED,
  MSG_PUBLISH_DONE,
  MSG_PUBLISH_NAMESPACE,
  MSG_PUBLISH_OK,
  MSG_REQUEST_ERROR,
  MSG_REQUEST_OK,
  MSG_REQUEST_UPDATE,
  MSG_SETUP,
  MSG_SUBSCRIBE,
  MSG_SUBSCRIBE_NAMESPACE,
  MSG_SUBSCRIBE_OK,
  MSG_TRACK_STATUS,
  SETUP_OPT_AUTHORITY,
  SETUP_OPT_MAX_AUTH_TOKEN_CACHE_SIZE,
  SETUP_OPT_MOQT_IMPLEMENTATION,
  SETUP_OPT_PATH,
} from './messages.js'

export {
  BIDIRECTIONAL_MESSAGES,
  CLIENT_ONLY_MESSAGES,
  CONTROL_MESSAGES,
  getLegalIncoming,
  getLegalOutgoing,
  SERVER_ONLY_MESSAGES,
} from './rules.js'
export type {
  ProtocolViolation,
  SessionPhase,
  SideEffect,
  TransitionResult,
  ValidationResult,
} from './session.js'
export { createDraft17SessionState, Draft17SessionFSM } from './session.js'

export type {
  DatagramObject,
  DataStreamEvent,
  DataStreamHeader,
  Draft17BaseMessage,
  Draft17DataStream,
  Draft17Fetch,
  Draft17FetchOk,
  Draft17GoAway,
  Draft17Message,
  Draft17MessageType,
  Draft17Namespace,
  Draft17NamespaceDone,
  Draft17Params,
  Draft17Publish,
  Draft17PublishBlocked,
  Draft17PublishDone,
  Draft17PublishNamespace,
  Draft17PublishOk,
  Draft17RequestError,
  Draft17RequestOk,
  Draft17RequestUpdate,
  Draft17Setup,
  Draft17SetupOptions,
  Draft17Subscribe,
  Draft17SubscribeNamespace,
  Draft17SubscribeOk,
  Draft17TrackProperties,
  Draft17TrackStatus,
  FetchObjectPayload,
  FetchStream,
  FetchStreamHeader,
  JoiningFetch,
  LargestObject,
  ObjectPayload,
  StandaloneFetch,
  SubgroupStream,
  SubgroupStreamHeader,
  SubscriptionFilter,
  UnknownParam,
} from './types.js'
