// Draft-18 codec entry point

export const DRAFT_VERSION = 0xff000012n

export type { Draft18Codec } from './codec.js'
export {
  createDataStreamDecoder,
  createDraft18Codec,
  createFetchStreamDecoder,
  createStreamDecoder,
  createSubgroupStreamDecoder,
  decodeDatagram,
  decodeDataStream,
  decodeFetchStream,
  decodeMessage,
  decodeSubgroupStream,
  encodeDatagram,
  encodeFetchStream,
  encodeMessage,
  encodeSubgroupStream,
} from './codec.js'
export type {
  DataStreamResetCodeValue,
  PublishDoneCodeValue,
  RequestErrorCodeValue,
  SessionTerminationCodeValue,
} from './error-codes.js'
export {
  DataStreamResetCode,
  PublishDoneCode,
  RequestErrorCode,
  SessionTerminationCode,
} from './error-codes.js'

export {
  MESSAGE_ID_MAP,
  MESSAGE_TYPE_MAP,
  MSG_FETCH,
  MSG_FETCH_OK,
  MSG_GOAWAY,
  MSG_NAMESPACE,
  MSG_NAMESPACE_DONE,
  MSG_PUBLISH,
  MSG_PUBLISH_BLOCKED,
  MSG_PUBLISH_DONE,
  MSG_PUBLISH_NAMESPACE,
  MSG_PUBLISH_OK,
  MSG_REQUEST_ERROR,
  MSG_REQUEST_OK,
  MSG_REQUEST_UPDATE,
  MSG_SETUP,
  MSG_SUBSCRIBE,
  MSG_SUBSCRIBE_NAMESPACE,
  MSG_SUBSCRIBE_OK,
  MSG_SUBSCRIBE_TRACKS,
  MSG_TRACK_STATUS,
  SETUP_OPT_AUTHORITY,
  SETUP_OPT_AUTHORIZATION_TOKEN,
  SETUP_OPT_MAX_AUTH_TOKEN_CACHE_SIZE,
  SETUP_OPT_MOQT_IMPLEMENTATION,
  SETUP_OPT_PATH,
} from './messages.js'

export {
  BIDIRECTIONAL_MESSAGES,
  CLIENT_ONLY_MESSAGES,
  CONTROL_MESSAGES,
  getLegalIncoming,
  getLegalOutgoing,
  SERVER_ONLY_MESSAGES,
} from './rules.js'
export type {
  ProtocolViolation,
  SessionPhase,
  SideEffect,
  TransitionResult,
  ValidationResult,
} from './session.js'
export { createDraft18SessionState, Draft18SessionFSM } from './session.js'

export type {
  DatagramObject,
  DataStreamEvent,
  DataStreamHeader,
  Draft18BaseMessage,
  Draft18DataStream,
  Draft18Fetch,
  Draft18FetchOk,
  Draft18GoAway,
  Draft18Message,
  Draft18MessageType,
  Draft18Namespace,
  Draft18NamespaceDone,
  Draft18Params,
  Draft18Publish,
  Draft18PublishBlocked,
  Draft18PublishDone,
  Draft18PublishNamespace,
  Draft18RequestError,
  Draft18RequestOk,
  Draft18RequestUpdate,
  Draft18Setup,
  Draft18SetupOptions,
  Draft18Subscribe,
  Draft18SubscribeNamespace,
  Draft18SubscribeOk,
  Draft18SubscribeTracks,
  Draft18TrackProperties,
  Draft18TrackStatus,
  FetchObjectPayload,
  FetchStream,
  FetchStreamHeader,
  JoiningFetch,
  LargestObject,
  ObjectPayload,
  Redirect,
  StandaloneFetch,
  SubgroupStream,
  SubgroupStreamHeader,
  SubscriptionFilter,
  UnknownParam,
} from './types.js'
